### ISSUE TITLE
Scale_data function results in addition of NaN values

### ISSUE THREAD

**Issue by Charliearg-ui** [ljhowell/machine-learning_CHD#5]
When using "def scale_data(data, method='std'):" 
![Screenshot 2019-11-01 at 10 33 49](https://user-images.githubusercontent.com/56122930/68019263-22751000-fc93-11e9-9351-6410b00c1849.png)
 missing (NaN) values appear in my data set, even after applying the function to processed data where missing values have been removed / replaced. 
In the screenshot below, the top part is a scaled version of bottom part - showing missing values appearing.

**Comment by ljhowell** [comment]
@Charliearg-ui I have looked into it but am struggling to reproduce this issue. Can you please include some more steps and show me exactly what you did to process the data such that the bug happens? Thanks.

I ran this code:
```
import preprocessing_ml as prep

dataset = pd.read_csv('framingham.csv')

d2 = prep.drop_missing(dataset)
d3 = prep.scale_data(d2,method='standard')
print(d3.isnull().sum())
```

and the output didn't suggest any NaN values are being introduced:
```
male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64
```

**Comment by ljhowell** [comment]
I fixed a bug with the function that may be related, where if you scale the TenYearCHD column it breakes things so I excluded this from the scaling

**Comment by ljhowell** [comment]
I think I bumped into a similar/the same bug as you found @Charliearg-ui 
It appeared to be related to an indexing isse when scale_data is used on a DataFrame with out of order indicies such as that produced from drop_values. This is fixed by resetting indicies after values are dropped:

Change to drop_missing in preprocessing_ml.py
`
return dataset2 ----> return dataset2.reset_index(drop=True)
`

Please test and if you are happy close the ticket

**Comment by eleanorjbarr** [comment]
I have tested this on K-neighbors, SVM and neural networks, so everything works on my end

**Comment by ljhowell** [comment]
Closing as verified fixed by @eleanorjbarr
