### ISSUE TITLE
Data Conversion exception when decimal input to any field on interface

### ISSUE THREAD

**Issue by ljhowell** [ljhowell/machine-learning_CHD#8]
When a decimal is input into one of the text boxes in the interface, a type error is raised:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\lewma\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-3-3aee3a021e62>", line 92, in <lambda>
    root.bind(root, (lambda event, e=ents: fetch(e)))
  File "<ipython-input-3-3aee3a021e62>", line 22, in fetch
    text  = int((entry[1].get()))
ValueError: invalid literal for int() with base 10: '32.'`

**Comment by ljhowell** [comment]
Fix with data wrong conversion in fetch function call. Fixed in commit 209efb7

`text  = int((entry[1].get()))\n"`
changed to: 
`text  = float((entry[1].get()))\n",`

Fix where fetch was happening in mainloop causing erros as code was continually calling fetch. Fixed in 1c21b3f

removed    
`root.bind(root, (lambda event, e=ents: fetch(e))) `
from mainloop

Changes pushed to master
@eleanorjbarr can you please test and close when you are happy

**Comment by eleanorjbarr** [comment]
I have tested this, happy with the outcome thankyou!
