### ISSUE TITLE
Interface quit button causes window to crash

### ISSUE THREAD

**Issue by ljhowell** [ljhowell/machine-learning_CHD#9]
Pressing the 'quit' button causes the python tkinter window to stop responding and eventually crash.

Using tk v. 8.6.9 with Windows 10

@eleanorjbarr does this happen for you also?

**Comment by eleanorjbarr** [comment]
Oh yes, I'm not sure why that is happening. Will have a look into it

**Comment by eleanorjbarr** [comment]
I have updated the code with a quite function, invoking root.destroy() followed by exit, as opposed to before where it was just root.quit(). Should be all good now, so Lewis if you check on your and are happy with it

**Comment by ljhowell** [comment]
root.destroy() works perfectly. Closing ticket as fixed
